### ISSUE TITLE
Default assignee when creating a task

### ISSUE THREAD

**Issue by visibilityspots** [TehShrike/k#2]
I assumed that when creating a new task it was autoassigned to the user who created the issue through the kanbanize-cli. 

I hardcoded my user as assignee in the index.js file but maybe this should become some sort of option in this great tool?

**Comment by TehShrike** [comment]
Hmm, interesting.  In our setup, tasks get automatically assigned to you when you move them to the "in progress" column.

Some boards may not have a magical "I'm working on it" column that sets them as the assignee automatically.

Still, for tests created in the backlog, setting the user who created it as assigned seems weird - maybe the app should wait and assign you to the task when you run the `k work [taskid]` command?

**Comment by visibilityspots** [comment]
That's a cool approach too, only thinking how you are going to get the tasks id from within the command line only? Right know if I run k tasks it gets an overview of my assigned tasks. For the others you still have to look them up through the gui or api call?

**Comment by TehShrike** [comment]
Yeah, right now the only way to see all tasks is if you clear your username, which is kind of jankety.  Maybe I should add a "`k tasks all`" command that doesn't apply the user filter so that you can see the whole list whenever you feel like it...

**Comment by visibilityspots** [comment]
Adding the "k tasks all" and the assignment when executing "k work on" would be a huge step forward in our case.

**Comment by TehShrike** [comment]
Sounds good to me.  I wrote those individual changes up as #3 and #4.  Feel free to open up pull requests for either, otherwise I'll see if I can make those changes some time this week.  Thanks!

**Comment by TehShrike** [comment]
I published both those changes in 1.3.0, let me know how it works for you!

**Comment by visibilityspots** [comment]
Great we just tested both of them and they are working as we discussed. This is already a great improvement. Only we where wondering about a lane option. So you could give up a lane which shows you for example all tasks only from that lane?

In anyway a big thanks already for your fast interaction!

**Comment by TehShrike** [comment]
You can currently set the lanes that you're interested in using `k set columns`, is that what you're asking about?  Or are you looking to pass in a lane name to the `k tasks` command?

**Comment by visibilityspots** [comment]
I probably misused the lane description, I ment the horizontal flow on a board..

**Comment by TehShrike** [comment]
You can define what horizontal flow you want to show up by running `k set columns Backlog,In Progress,Done`.  Only those columns will show up when you run `k tasks all`.

**Comment by visibilityspots** [comment]
We have many different horizonal lanes which each has those vertical
columns Backlog,progress,done etc..

like feature_X
underneath has a feature_Y

all on the same board..

So instead of having a seperate divider of vertical columns we a devider
for the horizontal lanes would be great too.

On Wed, Sep 16, 2015 at 09:06:44AM -0700, Josh Duff wrote:
> You can define what horizontal flow you want to show up by running `k set columns Backlog,In Progress,Done`.  Only those columns will show up when you run `k tasks all`.
> 
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/TehShrike/k/issues/2#issuecomment-140789509

-- 
Jan Collijs <jan@visibilityspots.com>
+32 (479) 586488 | http://visibilityspots.org

**Comment by TehShrike** [comment]
I think you might be confusing horizontal and vertical?  And maybe you're talking about swimlanes?

The [get_all_tasks](https://kanbanize.com/api#get_all_tasks) endpoint doesn't let you filter by swimline, but the results do include the lane name, so client-side filtering is possible.

Before I write up a task for that, is that actually what you were talking about?

**Comment by visibilityspots** [comment]
Yep, that's totally what I ment. My apologies for the inconvience about
it. We just started to use kanbanize and I'm not yet familiar with all
the syntax stuff :)

On Wed, Sep 16, 2015 at 08:29:38PM -0700, Josh Duff wrote:
> I think you might be confusing horizontal and vertical?  And maybe you're talking about swimlanes?
> 
> The [get_all_tasks](https://kanbanize.com/api#get_all_tasks) endpoint doesn't let you filter by swimline, but the results do include the lane name, so client-side filtering is possible.
> 
> Before I write up a task for that, is that actually what you were talking about?
> 
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/TehShrike/k/issues/2#issuecomment-140959409

-- 
Jan Collijs <jan@visibilityspots.com>
+32 (479) 586488 | http://visibilityspots.org

**Comment by visibilityspots** [comment]
I contacted https://kanbanize.com upstream by asking if the get_all_tasks endpoint could enhance the swimlane filtering option. Will keep you posted about an answer on this one.

**Comment by TehShrike** [comment]
Filtering client-side wouldn't be difficult either.  Were you imagining a global setting that you could change like all the other `k set` commands?

**Comment by visibilityspots** [comment]
In my particular use case I'm working on one swimming lane so the k set command would be fine. But some colleagues are working on different swimming lanes, guess that setting the needed swimming lanes through k set would be fine too and a default on all swimming lanes if that's feasible in some way?
