### ISSUE TITLE
Just a clue -- 

### ISSUE THREAD

**Issue by GabrielGab** [TehShrike/k#9]
Hi , I would like to add a "logging hour" functionality to this library .
2 questions 
   May you add it ??
   If not , may you provide a clue for doing that ??

I know that the API, for doing it in Kanbanize , is available , but I would like to add it into your library .
Gabriel

**Comment by TehShrike** [comment]
I'm open to any new features.  I'm not able to maintain or develop this any more, as I'm not using Kanbanize now, but I would be willing to help you add any thing you want to add.

What would this "logging hour" functionality look like?  How do you imagine using it?  Do you have any specific questions about the code?
